### ISSUE TITLE
This is a first test issue to test GitHub - Gropius - Jira sync functionality (mit Änderung)

### ISSUE THREAD

**Issue by spethso** [spethso/gropius-sync-test#1]
Lorem ipsum dolor sit amet

**Comment by spethso** [comment]
Here comes a comment 👍

**Comment by chriku** [comment]
Here comes a comment 👍

**Comment by chriku** [comment]
Wow, this is actually working 🙂

**Comment by chriku** [comment]
One gropius comment incoming

**Comment by chriku** [comment]
One gropius comment incoming

**Comment by spethso** [comment]
First closing

**Comment by chriku** [comment]
First closing

**Comment by chriku** [comment]
Here comes a comment 👍

**Comment by chriku** [comment]
Here comes a comment 👍

**Comment by chriku** [comment]
Wow, this is actually working 🙂

**Comment by chriku** [comment]
One gropius comment incoming

**Comment by chriku** [comment]
One gropius comment incoming

**Comment by chriku** [comment]
First closing

**Comment by chriku** [comment]
First closing
